name-template: "v$NEXT_PATCH_VERSION 🚀" # Simpler and more standard version naming
tag-template: "v$NEXT_PATCH_VERSION" # Standard tag naming with 'v' prefix
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)" # Clear and concise change log entry
change-title-escapes: '\"<>`' # Escape potentially problematic characters
version-resolver:
  major:
    labels:
      - "major" # Any label that indicates a major change
  minor:
    labels:
      - "minor" # Any label that indicates a minor change
  patch:
    labels:
      - "patch" # Default to patch for most changes
  default: patch # Default version bump if no label found
template: |
  ## What's Changed
  $CHANGES

  ## 🚀 Features
  $FEATURES

  ## 🐛 Bug Fixes
  $BUG_FIXES

  ## 🧰 Maintenance
  $MAINTENANCE

  ## Contributors
  Thanks to everyone who contributed to this release:
  $CONTRIBUTORS
