version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 657214731516.dkr.ecr.us-west-2.amazonaws.com/carai-api:1.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:3000
    environment:
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - NODE_OPTIONS=${NODE_OPTIONS}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
