version: "3.8"

services:
  api:
    build: .
    image: carai-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:3000
    environment:
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - NODE_OPTIONS=${NODE_OPTIONS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
