version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PORT}:3000"
    env_file:
      - variables.env
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
