name: Continuous Integration Tests

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14", "16", "18"]

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2376:2376

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Pull Node.js Docker Image
        run: docker pull node:18

      - name: Pull Python Docker Image
        run: docker pull python:3.8

      # Start any required Docker containers here
      - name: Start Required Docker Containers
        run: |
          docker run -d --name some-service-name service-image:tag
          # Replace 'some-service-name' and 'service-image:tag' with your actual service details
          # Add additional docker run commands as needed for other services

      - name: Run Tests
        run: npm run test:ci

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: coverage/icov-report/

      - name: Notify failure via Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚨 A commit failed tests in ${{ github.repository }} 🚨
            - Author: ${{ github.actor }}
            - Commit Message: ${{ github.event.head_commit.message }}
            - Commit SHA: ${{ github.sha }}
            - PR: ${{ github.event.pull_request.title || 'N/A' }}
            - Check: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
